export const loginContant = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCESS: 'LOGIN_SUCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
};
export const logoutContant = {
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCESS: 'LOGOUT_SUCESS',
  LOGOUT_FAILED: 'LOGOUT_FAILED',
};
